name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up environment variables
      shell: powershell
      run: |
        $git_hash = (git log -n 1 --pretty=%h).Trim()
        $git_tag = git tag -l --points-at HEAD
        $git_version = If (![string]::IsNullOrWhitespace($git_tag)) { $git_tag } Else { $git_hash }

        Add-Content "$env:GITHUB_ENV" "GIT_HASH=$git_hash"
        Add-Content "$env:GITHUB_ENV" "GIT_TAG=$git_tag"
        Add-Content "$env:GITHUB_ENV" "GIT_VERSION=$git_version"
        Add-Content "$env:GITHUB_ENV" "PYTHONIOENCODING=utf-8"

        echo "Got version '$git_version'"

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x

    - name: Set up Python 3
      uses: actions/setup-python@v2.1.3
      with:
        python-version: 3.x

    - name: Fetch Beat Saber Bindings
      uses: actions/checkout@v2
      with:
        repository: nicoco007/BeatSaberBindings
        token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        path: BeatSaberBindings\Beat Saber_Data\Managed

    # this should eventually be turned into a task or action
    - name: Set manifest version
      run: python bsipa_version_hash.py "Source\CustomAvatar\manifest.json" "Source\CustomAvatar\Properties\AssemblyInfo.cs"

    - name: Build Debug
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Debug -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.GIT_VERSION }}-DEBUG
        path: Source\CustomAvatar\bin\Debug\netstandard2.0

    - name: Build Release
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Release -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.GIT_VERSION }}-RELEASE
        path: Source\CustomAvatar\bin\Release\netstandard2.0

    - name: Build Editor
      run: dotnet build Source\CustomAvatar-Editor\CustomAvatar-Editor.csproj -c Release -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Editor
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.GIT_VERSION }}-Editor
        path: Source\CustomAvatar-Editor\bin\Release\netstandard2.0